### ISSUE TITLE
browser compatibility

### ISSUE THREAD

**Issue by CorneeldH** [felixrupp/owncloud-files_clipboard#31]
Hi there,

Thanks for the great app. We got a complaint from one user that the app wasn't working: we found out it was most likely due to his half-year old Safari browser. It makes sense that you dont support every (older) version of every browser, however do you a browser compatibility list somewhere?

Thanks!

**Comment by leizh** [comment]
files_clipboard should work on the same browser version than the nextcloud/owncloud core. I have checked the code and fixed a javascript syntax issue which is certainly the origin of this (a986786e04a5bc8feaece48e9d97576f456aa75f).

**Comment by CorneelDragon** [comment]
Just to let you know: My users still experience the problem on old browser version (in their case Safari 9.01 (11601.2.7.2).

**Comment by leizh** [comment]
Thanks for the report but I can't resolve it without knowing the javascript error. I have reopened the issue.
