### ISSUE TITLE
Cut functionality in shared folders without deleting ability  

### ISSUE THREAD

**Issue by SDETABC** [felixrupp/owncloud-files_clipboard#36]
I have one case. I shared a root folder for one group of users with all rights except deleting one.  
The folder has a large structure of files and folders.
When a user of the group trying to cut some file and paste it in the right place (in the root folder to subfolders) he met one problem. The system thinks that he wants to delete the file, but he just want to change it and move to the subfolder 
If the file is moved within the root folder to the subfolder, can the system see that the file is being moved within the given root folder and not deleted? 
![440dcd54b1](https://user-images.githubusercontent.com/18512433/35804724-9b664516-0a81-11e8-9228-36f9e5d624e9.jpg)

**Comment by felixrupp** [comment]
Hi @SDETABC 

That’s currently not possible. If you are using Nextcloud > 16, please rely on the core copy--cut-paste feature and don't use files_clipboard.

Regards,
Felix
