### ISSUE TITLE
nextcloud 13 support?

### ISSUE THREAD

**Issue by toastbrotch** [felixrupp/owncloud-files_clipboard#38]
i like your app, as its an easy problem-solver for a really stupid missing-feature in nextcloud...

**Comment by bowmasters** [comment]
Nextcloud 13 now has this functionality builtin, so no need for a separate app anymore

**Comment by GammaPi** [comment]
@bowmasters Where's the built-in clipboard functionality? I couldn't find it. The only thing I can use is the reluctant move/copy function requiring the user to choose saving path from root manually every time.
