### ISSUE TITLE
Place for paste-icon is irritating

### ISSUE THREAD

**Issue by raschid** [felixrupp/owncloud-files_clipboard#42]
installed files clipboard on 10.0.10.4 in shared hosting and it works like a charm.
BUT it took me a while to find out, how to paste files, i copied or cut out before.

So instead of having the function cut/copy on the far right plus hidden in the context menu of marked files/folders, while the paste-function is only available on the far left as an icon besides the plus-icon, i wish there was a more consistent solution.

The most obvious solution for me would be, to put a "paste"-link exactly where the cut or copy-links are.

**Comment by felixrupp** [comment]
Hi @raschid 

the paste-icon is placed on top, because that’s currently the only way to implement a folder-wide action. Actions in the context-menu while in a folder only apply to single (or a group of) files, not the folder you are in.

Greetings,
Felix
