### ISSUE TITLE
Issue owncloud 10.1 signature

### ISSUE THREAD

**Issue by rediumbv** [felixrupp/owncloud-files_clipboard#44]
HI,

I get the follow error when i change the info.xml 

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_clipboard
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\MissingSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [files_clipboard] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\MissingSignatureException
                    [message] => Signature data not found.
                )

        )

)

How to fix it.

**Comment by felixrupp** [comment]
Hello @rediumbv 

after I got the ownership of the files_clipboard app from [leizh](https://github.com/leizh), I released a signed version (1.0.0) with support including oC 10.3.*.

The app will soon be available through the marketplace, until then you can already download it in the [release-section](https://github.com/felixrupp/owncloud-files_clipboard/releases).

Have fun and regards,
Felix
