### ISSUE TITLE
Owncloud 10.2

### ISSUE THREAD

**Issue by srjosue** [felixrupp/owncloud-files_clipboard#45]
Not working in version 10.2

**Comment by prsnbrg** [comment]
The same as [#43](https://github.com/leizh/owncloud-files_clipboard/issues/43)?

**Comment by dlandon** [comment]
Please release an updated version to the Marketplace.

**Comment by GettinBissi** [comment]
I love this app but it doesn't work with 10.2. Please release an updated copy.

**Comment by lighthousebulb** [comment]
Yes, please update your awesome app!

**Comment by tedstrauss** [comment]
My users love the clipboard. +100

**Comment by tedstrauss** [comment]
Little tip: If you edit the following line, and raise the number 10 to say... 11, and then enable the app, it should work. (It worked for me.)

https://github.com/leizh/owncloud-files_clipboard/blob/b84c2f0f24c6449d255374c05a81148fa7df717a/appinfo/info.xml#L18

I'm pretty sure this voids the warranty though :)

**Comment by dlandon** [comment]
That's all well and good, but doing this generates an error and the app should really be available on the Marketplace, which it is not at this time because of the version issue.

**Comment by dlandon** [comment]
Could you please update this app to work on ownCloud 10.2!

**Comment by felixrupp** [comment]
Hello @srjosue @dlandon @prsnbrg @GettinBissi @lighthousebulb @tedstrauss 

after I got the ownership of the files_clipboard app from [leizh](https://github.com/leizh), I released a signed version (1.0.0) with support including oC 10.3.*.

The app will soon be available through the marketplace, until then you can already download it in the [release-section](https://github.com/felixrupp/owncloud-files_clipboard/releases).

Have fun and regards,
Felix

**Comment by dlandon** [comment]
Thank you very much!

**Comment by leizh** [comment]
Sorry everyone for not having maintained this project properly and for the lack of answer. I am glad it will continue in the hands of felixrupp.
