### ISSUE TITLE
ownCloud 10.3.1

### ISSUE THREAD

**Issue by cdamken** [felixrupp/owncloud-files_clipboard#46]
It would be great to have a new release from your app in Marketplace

**Comment by taich001** [comment]
Yes I would also greatly appreciate it.
Is there anything I can contribute?

**Comment by phil-davis** [comment]
@leizh can you do a release of this app?

**Comment by felixrupp** [comment]
Hello @cdamken @taich001 @phil-davis 

after I got the ownership of the files_clipboard app from [leizh](https://github.com/leizh), I released a signed version (1.0.0) with support including oC 10.3.*.

The app will soon be available through the marketplace, until then you can already download it in the [release-section](https://github.com/felixrupp/owncloud-files_clipboard/releases).

Have fun and regards,
Felix
