### ISSUE TITLE
URGENT: App dependency max version

### ISSUE THREAD

**Issue by mmattel** [felixrupp/owncloud-files_clipboard#49]
@felixrupp Thanks for taking over this repro :smile:

Just have seen that it was updated on marketplace.

Please **urgent** update the `appinfo/info.xml` dependency (and push to marketplace)

From
```
    <dependencies>
        <owncloud min-version="9.0" max-version="10.3" />
```
To
```
    <dependencies>
        <owncloud min-version="9.0" max-version="10" />
```
This allows this app being used in all ownCloud versions to any release >= 9.0 but max in the 10.x range without being restricted to a subversion.

A new release (10.4) is close to be published and having that restriction would immediately make it unusable again... 

Please also see https://github.com/felixrupp/owncloud-files_clipboard/pull/41 which exactly merged this change. No idea why this was lost on the transition to you.

**Comment by felixrupp** [comment]
Hi @mmattel,

Sorry for the inconvenience, I don’t know where this merge has gone, will release a minor version with max-version="10" soon!

Thanks for notifying me,

Felix

**Comment by felixrupp** [comment]
Hi @mmattel,

version 1.0.1 has just been released!


Regards,

Felix
