### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by mmattel** [felixrupp/owncloud-files_clipboard#50]
Hello @felixrupp 

IMHO, README.md could be improved a little bit.

For a manual installation via github you should note that it is necessary to add a config.php parameter
```
  'integrity.ignore.missing.app.signature' =>
    array (
     0 => 'files_clipboard',
    ),
```
And it is adviced, in case of owncloud, to install via marketplace which does not need any config parameter because it is signed.

You have a new release 1.0.1 :smile:

**Comment by felixrupp** [comment]
Hi @mmattel,

you are encouraged to change the Readme according to your suggestion and provide a pull request. I will be happy to merge it then!


Regards,
Felix
