### ISSUE TITLE
how can I add force option for overwritting ?

### ISSUE THREAD

**Issue by gontz** [felixrupp/owncloud-files_clipboard#52]
Hello,

How can I add an overwrite option when copying. If the same filename  exists in the target directory, I get an error "no permission to write"

I would like to be able to tell it, yes, overwrite it.

How can I do that?

**Comment by felixrupp** [comment]
Hello @gontz 

that’s currently not possible, sorry. I’ll add it to my list of feature-requests.

Regards,
Felix

**Comment by felixrupp** [comment]
Feature could be implemented with #35.
